analytics: {}
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.527871
  lightness: 0.504223
  rhythmicContrast: 0.78125
  saturation: 0.758445
cta: {}
layout_spectrum: 0.70777
name: WOMAN
opengraph: {}
purpose: []
typography_spectrum: 0.663006
