name: WOMAN
favicon: null
layout_spectrum: 0.68266
typography_spectrum: 0.24317
title: Words of Mouth Advertising Network
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eceff1'
    - '#1bb0c3'
    - '#000000'
    - '#004040'
    - '#8b8b8b'
  brandStrength: 0.125
  lightness: 0.625
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
