name: WOMAN
favicon: null
layout_spectrum: 0.63048
typography_spectrum: 0.6055
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
