name: WOMAN
favicon: null
layout_spectrum: 0.89482
typography_spectrum: 0.22648
title: Word of Mouth Advertising & Networking
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eceff1'
    - '#1bb0c3'
    - '#000000'
    - '#004040'
    - '#8b8b8b'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
