name: W.O.M.A.N
favicon: null
layout_spectrum: 0.74077
typography_spectrum: 0.6353
title: Words of Mouth Advertising Network
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#565656'
    - '#ec7a08'
    - '#cc0000'
    - '#3f9c35'
  brandStrength: 0
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
