name: WOMAN
favicon: null
layout_spectrum: 0.99107
typography_spectrum: 0.22648
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d7dcd6'
    - '#2c436d'
    - '#f0b5a3'
    - '#b78d8e'
  brandStrength: 0.4375
  lightness: 0.6875
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
