name: WOMAN
favicon: null
layout_spectrum: 0.08403
typography_spectrum: 0.22648
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5e5e5'
    - '#201e21'
    - '#4e96b0'
    - '#ff5252'
    - '#82d341'
  brandStrength: 0.625
  lightness: 0.625
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
