name: WOMAN
favicon: null
layout_spectrum: 0.99107
typography_spectrum: 0.22648
title: 'Word of Mouth Advertising & Networking'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#4c2611'
    - '#d0a787'
    - '#4a6d69'
    - '#ffd6bc'
  brandStrength: 0.4375
  lightness: 0.6875
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
